spring:
    mail:
        host: smtphz.qiye.163.com
        username: astrosea@astrosea.io
        password: Yzmvq5UjMjCz65wU
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    # 德国服务器 944 端口才能用
                    port: 994
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        enable: true
        default-encoding: utf-8
        from: admin@astrosea.io

    jackson:
        time-zone: GMT+8

    application:
        name: Astro-Richer

    datasource:
        # 配置数据源类型为 Hikari 数据源
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/astro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#        线上
#        username: astro
#        password: 123456

        #       本地 & 线上
        username: astro
        password: NT8ALGJBnMEWCdYM

#         测试环境
#        username: astro
#        password: 123456

    redis:
        host: localhost
        port: 6379
        password: 123@jiaru
#        password:


server:
    port: 8717    #HTTPS协议默认端口号为443，需要使用其他端口时，您可以在此处自定义。
    ssl:
        key-alias: astroseaSSL200    #证书别名
        key-store-password: 123astrosea   #填写pfx-password.txt文件内的密码。
        key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PCKS12。
        key-store: classpath:ssl249.jks   #您需要使用实际的证书名称替换domain_name.pfx。
        trust-store: classpath:ssl249.jks
        trust-store-password: 123astrosea

mybatis-plus:
    global-config:
        db-config:
            field-fill:
                enable: true # 启用自动填充功能
            id-type: auto
            logic-delete-field: deleted

oss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    accessKeyId: LTAI5tDVfYcwqZfZbq1rjty3
    accessKeySecret: upjBZG9TcN9jn3Z2ybvPqrJgqP3Lrn
    bucketName: astrosea-bucket








